
   Name           Domain             Range
   ----------------------------------------
   inc            .1                 .2
   pdsr 2         <.3,.4>            .5
   ----------------------------------------
   inc            .2                 .6
   inc            .5                 .7
   ----------------------------------------
   inc            .6                 .8
   sdpr 2         .7                 <.9,.10>
   sdpr 2         .7                 <.9,.10>
   ----------------------------------------

 Directions -  <in,<in,in>> ~ <out,<out,out>>

 Wiring -  <.1,<.3,.4>> ~ <.8,<.9,.10>>

 Inputs -  .1 .3 .4
